# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89409a2cccda2f1d6ea829e0fdce28c80260034c3ad9ecc3c8364e440bca8266be211c02c07a3efdfa69f4ce7922f762d8f6a0f247012ef5c22fa7365da72ba

test:
  secret_key_base: 47e0525682202b012e816ee579d27be7d4c155c053f93b8ac0b125fd57865160d06c79a23af12075b9a456cb9cb2c1fdb3d4c3ba9108d05cff916ce1283b1798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
